export const services = [
  {
    id: "ia-politica",
    icon: "brain",
    title: "IA Politica",
    subtitle: "Posicionamiento Estrategico",
    description:
      "Analisis de sentimiento, optimizacion de mensajes y estrategia de comunicacion politica con IA.",
    features: [
      "Analisis de sentimiento en tiempo real",
      "Optimizacion de mensajes clave",
      "Monitoreo de percepcion publica",
      "Reportes estrategicos personalizados",
      "Entrega de reporte en 3 dias en pdf",
      "Nos ajustamos a tus necesidades",
    ],
    price: 300000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "smm-crecimiento",
    icon: "users",
    title: "SMM Crecimiento",
    subtitle: "Pack Completo de Redes",
    description:
      "Aumenta tu presencia en redes sociales con seguidores y engagement.",
    features: [
      "5,000 seguidores",
      "10,000 likes",
      "500 comentarios personalizados",
      "100 viewers para lives",
      "Entrega del servicios puede ser diario, mensual o semanal",
    ],
    price: 250000,
    popular: true,
    requiresDiagnostic: false,
  },
  {
    id: "combo-total",
    icon: "zap",
    title: "Combo Total",
    subtitle: "IA + SMM Integrado",
    description:
      "La solucion definitiva combinando IA politica y crecimiento en redes.",
    features: [
      "Todo lo de IA Politica",
      "Todo lo de SMM Crecimiento",
      "Estrategia integrada",
      "Soporte prioritario 24/7",
      "Nos ajustamos a tus necesidades",
    ],
    price: 500000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "victoria-360",
    icon: "trophy",
    title: "Victoria 360",
    subtitle: "Ingeniería de Victoria Total",
    description:
      "La solución definitiva para campañas ganadoras: Tráfico masivo con Ads, Landing Pages psicométricas y análisis de intención de voto con IA de última generación.",
    features: [
      "Ads de Tráfico Masivo (Meta, Google, TikTok)",
      "Landing Page con Test de Personalidad Psicográfico",
      "Detección de Problemáticas por Micro-segmentación",
      "Análisis de Intención de Voto Basado en Datos IA",
      "Ingeniería de Mensaje: ¿Qué quiere escuchar el elector?",
      "Dashboard de Sentimiento Social en Tiempo Real",
      "Configuración de Respuesta Automatizada IA",
      "Soporte Estratégico de Elite 24/7",
    ],
    price: 15000000,
    popular: false,
    requiresDiagnostic: true,
  },
]
