export const services = [
  {
    id: "ia-politica",
    icon: "brain",
    title: "IA Política",
    subtitle: "Posicionamiento Estratégico",
    description:
      "Domina la narrativa digital con análisis de sentimiento avanzado, optimización psicográfica de mensajes y monitoreo estratégico de la percepción ciudadana mediante IA.",
    features: [
      "Análisis de sentimiento social en tiempo real",
      "Optimización de mensajes y discursos clave",
      "Monitoreo de percepción y tendencias públicas",
      "Reportes estratégicos avanzados en PDF (3 días)",
      "Análisis de competidores y narrativa opositora",
      "Detección de 'Fake News' y alertas tempranas",
      "Segmentación de audiencias por intereses",
      "Consultoría personalizada según tus objetivos",
    ],
    price: 300_000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "smm-crecimiento",
    icon: "users",
    title: "SMM Crecimiento",
    subtitle: "Pack de Autoridad Digital",
    description:
      "Construye una presencia imponente y creíble en todas tus plataformas con un flujo constante de engagement real diseñado para proyectar liderazgo.",
    features: [
      "5,000 Seguidores de alta calidad y retención",
      "10,000 Likes distribuidos en tus publicaciones",
      "500 Comentarios personalizados estratégicos",
      "100 Viewers constantes para tus transmisiones",
      "Entrega flexible (diario, semanal o mensual)",
      "Mejora inmediata de la prueba social (Social Proof)",
      "Soporte para múltiples redes sociales",
      "Garantía de reposición ante caídas",
    ],
    price: 250_000,
    popular: true,
    requiresDiagnostic: false,
  },
  {
    id: "combo-total",
    icon: "zap",
    title: "Combo Total",
    subtitle: "Sinergia IA + Crecimiento SMM",
    description:
      "La solución integral definitiva: combina la inteligencia de datos estratégica con el crecimiento masivo para asegurar un impacto digital imparable.",
    features: [
      "Todo el poder de la IA Política Estratégica",
      "Todo el alcance del Pack SMM Crecimiento",
      "Estrategia integrada de contenido y autoridad",
      "Soporte prioritario VIP 24/7",
      "Optimización continua basada en resultados",
      "Dashboard de métricas unificado",
      "Análisis de impacto post-campaña",
      "Ajustes de estrategia en tiempo real",
    ],
    price: 500_000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "victoria-360",
    icon: "trophy",
    title: "Victoria 360",
    subtitle: "Ingeniería de Victoria Total",
    description:
      "La solución definitiva para campañas ganadoras: Tráfico masivo con Ads, Landing Pages psicométricas y análisis de intención de voto con IA de última generación.",
    features: [
      "Ads de Tráfico Masivo (Meta, Google, TikTok)",
      "Landing Page con Test de Personalidad Psicográfico",
      "Detección de Problemáticas por Micro-segmentación",
      "Análisis de Intención de Voto Basado en Datos IA",
      "Ingeniería de Mensaje: ¿Qué quiere escuchar el elector?",
      "Dashboard de Sentimiento Social en Tiempo Real",
      "Configuración de Respuesta Automatizada IA",
      "Soporte Estratégico de Elite 24/7",
    ],
    price: 15_000_000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "gestion-crisis",
    icon: "shield-alert",
    title: "Gestión de Crisis",
    subtitle: "Protección de Reputación 24/7",
    description:
      "Respuesta inmediata ante ataques digitales. Neutralizamos la narrativa negativa y protegemos tu imagen pública en tiempo real.",
    features: [
      "Monitoreo de alertas tempranas 24/7",
      "Neutralización de ataques masivos",
      "Gestión de comunicación de crisis",
      "Amplificación de contranarrativas",
      "Soporte legal digital especializado",
      "Reportes de impacto cada 6 horas",
    ],
    price: 1_200_000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "marca-elite",
    icon: "star",
    title: "Marca Personal Élite",
    subtitle: "Constucción de Liderazgo",
    description:
      "Transformamos tu perfil en un referente de opinión. Estrategia de contenido premium diseñada para proyectar autoridad y confianza.",
    features: [
      "Estrategia de Storytelling político",
      "Producción de contenido 4K mensual",
      "Gestión de relaciones públicas digitales",
      "Aumento orgánico de autoridad",
      "Consultoría de imagen y discurso",
      "Verificación de cuentas gestionada",
    ],
    price: 850_000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "monitor-oposicion",
    icon: "search",
    title: "Monitoreo de Oposición",
    subtitle: "Inteligencia Competitiva",
    description:
      "Anticípate a los movimientos de tus adversarios. Análisis profundo de sus estrategias, gastos y debilidades digitales.",
    features: [
      "Seguimiento de pauta de adversarios",
      "Análisis de comunidad opositora",
      "Detección de puntos débiles estratégicos",
      "Reportes comparativos semanales",
      "Alertas de movimientos en tiempo real",
    ],
    price: 1_500_000,
    popular: false,
    requiresDiagnostic: true,
  },
  {
    id: "ads-expert",
    icon: "megaphone",
    title: "Ads de Tráfico Masivo",
    subtitle: "Alcance Exponencial",
    description:
      "Maximiza tu visibilidad en Meta, Google y TikTok. Segmentación ultra-precisa para llegar exactamente al público que necesitas convencer.",
    features: [
      "Configuración avanzada de Pixel/API",
      "Diseño de artes y copies persuasivos",
      "Optimización diaria de presupuesto",
      "Micro-segmentación por intereses",
      "Retargeting estratégico avanzado",
    ],
    price: 2_500_000,
    popular: false,
    requiresDiagnostic: false,
  },
  {
    id: "militancia-digital",
    icon: "user-plus",
    title: "Militancia Digital",
    subtitle: "Activismo Coordinado",
    description:
      "Organiza a tu base de seguidores para defender y promover tu causa. Herramientas de coordinación masiva para redes.",
    features: [
      "Creación de grupos de respuesta rápida",
      "Material de difusión diario para bases",
      "Entrenamiento en defensa de marca",
      "Coordinación de tendencias compartidas",
    ],
    price: 600_000,
    popular: false,
    requiresDiagnostic: false,
  },
]
